INSERT INTO tb_modalidade (descricao) VALUES
('Atletismo'),
('Badminton'),
('Basquete'),
('Ciclismo'),
('Futsal'),
('Ginástica Rítmica'),
('Handebol'),
('Judô'),
('Natação'),
('Tênis de Mesa'),
('Vôlei'),
('Vôlei de Praia'),
('Wrestling');

INSERT INTO tb_escola (nome, endereco, site, email, diretor, telefone) VALUES
('Campus Aquidauana', 'Rua José Tadao Arima, 222, Bairro Ycaraí, CEP 79200-000, Aquidauana, MS', 
'https://www.ifms.edu.br/campi/campus-aquidauana', 'aquidauana@ifms.edu.br', 'Hilda Ribeiro Romero',  '(67) 3240-1600'), 
('Campus Campo Grande', 'Rua Taquari, 831, Bairro Santo Antônio, CEP 79.100-510, Campo Grande, MS', 
'https://www.ifms.edu.br/campi/campus-campo-grande', 'campo.grande@ifms.edu.br', 'Dejahyr Lopes Junior',  '(67) 3357-8501'), 
('Campus Corumbá', 'Rua Pedro de Medeiros, 941, Bairro Popular Velha, CEP 79310-110, Corumbá, MS', 
'https://www.ifms.edu.br/campi/campus-corumba', 'corumba@ifms.edu.br', 'Wanderson da Silva Batista', '(67) 3234-9101'), 
('Campus Coxim', 'Rua Salime Tanure, s/n, Bairro Santa Tereza CEP 79.400-000, Coxim, MS', 
'https://www.ifms.edu.br/campi/campus-coxim', 'coxim@ifms.edu.br', 'Angela Kwiatkowski', '(67) 3291- 9600'), 
('Campus Dourados', 'Rua Filinto Müller, 1.790, Jardim Canaã, CEP 79833-520, Dourados, MS', 
'https://www.ifms.edu.br/campi/campus-dourados', 'dourados@ifms.edu.br', 'Carlos Vinícius da Silva Figueiredo', '(67) 3410-8500'), 
('Campus Jardim', 'Rodovia BR-060, s/n, saída para Bela Vista, CEP 79.240-000, Jardim, MS', 
'https://www.ifms.edu.br/campi/campus-jardim', 'jardim@ifms.edu.br', 'Sirley da Silva Rojas Oliveira', '(67) 3209-0200'),
('Campus navirái', 'Rua Hilda, 203, Bairro Boa Vista, CEP 79950-000, Naviraí, MS', 
'https://www.ifms.edu.br/campi/campus-navirai', 'navirai@ifms.edu.br', 'Matheus Bornelli de Castro', '(67) 3409-2500');